services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql

  datomic:
    build:
      context: docker/datomic
      args:
        DATOMIC_VERSION: "1.0.7556"
    depends_on:
      - postgres
    ports:
      - "4334:4334"
    volumes:
      - ./docker/datomic/transactor.properties:/opt/datomic-pro/config/transactor.properties

volumes:
  pg-data:
